### ISSUE TITLE
license required?

### ISSUE THREAD

**Issue by aristosv** [cronet/docker-manager.io#6]
I installed it using this command

#!/bin/bash

```
docker pull cronet/manager.io:latest
docker run -d \
 --restart=always \
 --name manager \
 -h manager \
 -e PUID=1001 \
 -e PGID=1001 \
 -e TZ=Europe/Nicosia \
 --net=network \
 -p 8082:8080 \
 -v manager:/data \
 cronet/manager.io:latest
```

and I get a prompt to install a license. Is this normal? I may be wrong, but I was under the impression that it was free.

![Greenshot 2020-12-20 08 17 48](https://user-images.githubusercontent.com/528302/102706592-dc667b80-429b-11eb-984d-f7948f4f5033.png)

**Comment by anony253** [comment]
Hi aristosv,

This is normal. What you installed is a server edition of Manager, which does require a license to be used in production environment. Only desktop version of Manager is free. Please check the link to see more information: https://www.manager.io/server/ .

Server version is intended to be used in a larger environment and therefore a license requirement is there. Desktop version only supports a single user on a single device and it is free.

Hope this clarifies your concerns, please contact me if you have any more questions.

Regards,
Marko

**Comment by aristosv** [comment]
thanks for the info
